---
title: "pre-processing"
author: "Mirte Draaijer and Yamila Timmer"
date: "2025-02-16"
output: html_document
---

```{r}
library(data.table)
library(dplyr)
library(tidyr)
library(feather)
```

# Load data:
```{r}
expression_data <- fread("../../OmicsExpressionProteinCodingGenesTPMLogp1.csv")
meta_data <- fread("../../Model.csv", na.strings = c("", "unknown", "Unknown", "None")) 
# Both Unknown and unknown because they were both used in various columns and None was used for 
# Platecoating which was all equal to none, so row can be removed
```

# Change colname in expression data
```{r}
# Makes merging easier
colnames(expression_data)[1] <- "ModelID"
```

# Make expression data tidy:
```{r}
# Make the data tidy
tidy_data <- expression_data %>% 
            pivot_longer(
                cols = 2:ncol(expression_data),
                names_to = "gene",
                values_to = "expr")

```

# Removing entrez ID from the gene column:
```{r}
tidy_data$gene <- gsub(" \\(\\d+\\)", "", tidy_data$gene)
```


# Save the two seperate data files:
```{r}
write_feather(x = tidy_data, path = "expression_data.tsv")
write_feather(x = meta_data, path = "meta_data.tsv")
```

# Generating table with all pathways and corresponding genes:
```{r}
pathway_table <- getGeneKEGGLinks(species = "hsa")
pathway_table$Symbol <- mapIds(org.Hs.eg.db, pathway_table$GeneID, column="SYMBOL", keytype="ENTREZID")

write_feather(x=pathway_table, path=paste0(DATA_DIR, "pathway_table.tsv"))
```

# Generating table with humane pathway descriptions (for user selection)
```{r}

humane_pathways <- getKEGGPathwayNames(species="hsa")
write_feather(x=humane_pathways, path=paste0(DATA_DIR, "humane_pathways.tsv"))
```